routes:
  band_info:
    pattern: /band
    method: [ "get" ]
    controller: "H\Music\Controller\BandController::cget"
  band_add: 
    pattern: /band
    method: [ "post" ]
    controller: "H\Music\Controller\BandController::post"
  band_get:
    pattern: /band/%
    method: [ "get" ]
    controller: "H\Music\Controller\BandController::get"
  band_update: 
    pattern: /band/%
    method: [ "put" ]
    controller: "H\Music\Controller\BandController::put"
  band_delete: 
    pattern: /band/%
    method: [ "delete" ]
    controller: "H\Music\Controller\BandController::delete"
