controllers:
  account.controller:
    prefix: account
    class: H\Music\Controller\AccountController
    routes:
      baccountand.controller.create:
        pattern: /
        class: account.controller:create
        method: POST
      account.controller.update:
        pattern: /{id}
        class: account.controller:update
        method: PUT
        assert:
          id: \d+
      account.controller.delete:
        pattern: /{id}
        class: account.controller:delete
        method: DELETE
        assert:
          id: \d+
      account.controller.load:
        pattern: /{id}
        class: account.controller:load
        method: GET
        assert:
          id: \d+
      account.controller.find:
        pattern: /find
        class: account.controller:find
        method: GET
  band.controller:
    prefix: band
    class: H\Music\Controller\BandController
    routes:
      band.controller.create:
        pattern: /
        class: band.controller:create
        method: POST
      band.controller.update:
        pattern: /{id}
        class: band.controller:update
        method: PUT
        assert:
          id: \d+
      band.controller.delete:
        pattern: /{id}
        class: band.controller:delete
        method: DELETE
        assert:
          id: \d+
      band.controller.load:
        pattern: /{id}
        class: band.controller:load
        method: GET
        assert:
          id: \d+
      band.controller.find:
        pattern: /find
        class: band.controller:find
        method: GET
