controllers:

  api.controller:
    prefix: api
    class: H\Music\Controller\APIController
    routes:
      login:
        pattern: /login
        method: POST
      logout:
        pattern: /logout
        method: POST
      name:
        pattern: /name
        method: POST
      version:
        pattern: /version
        method: POST

  account.controller:
    prefix: api/account
    class: H\Music\Controller\AccountController
    routes:
      create:
        pattern: /
        method: POST
      update:
        pattern: /{id}
        method: PUT
        assert:
          id: \d+
      delete:
        pattern: /{id}
        method: DELETE
        assert:
          id: \d+
      load:
        pattern: /{id}
        method: GET
        assert:
          id: \d+
      find:
        pattern: /find
        method: GET

  band.controller:
    prefix: api/band
    class: H\Music\Controller\BandController
    routes:
      create:
        pattern: /
        method: POST
      update:
        pattern: /{id}
        method: PUT
        assert:
          id: \d+
      delete:
        pattern: /{id}
        method: DELETE
        assert:
          id: \d+
      load:
        pattern: /{id}
        method: GET
        assert:
          id: \d+
      find:
        pattern: /find
        method: GET
