controllers:

  common.controller:
    prefix: api
    class: H\Music\Controller\CommonController
    routes:
      info:
        pattern: /info
        method: GET
      login:
        pattern: /login
        method: POST
      logout:
        pattern: /logout
        method: POST

  account.controller:
    prefix: api/account
    class: H\Music\Controller\AccountController
    routes:
      create:
        pattern: /
        method: POST
      update:
        pattern: /{id}
        method: PUT
        assert:
          id: \d+
      delete:
        pattern: /{id}
        method: DELETE
        assert:
          id: \d+
      load:
        pattern: /{id}
        method: GET
        assert:
          id: \d+
      find:
        pattern: /find
        method: GET

  band.controller:
    prefix: api/band
    class: H\Music\Controller\BandController
    routes:
      create:
        pattern: /
        method: POST
      update:
        pattern: /{id}
        method: PUT
        assert:
          id: \d+
      delete:
        pattern: /{id}
        method: DELETE
        assert:
          id: \d+
      load:
        pattern: /{id}
        method: GET
        assert:
          id: \d+
      find:
        pattern: /find
        method: GET
