security:
  jwt:
    secret_key: key
    life_time: 86400
    options:
      username_claim: sub
      header_name: X-Access-Token
      token_prefix: Bearer
  firewalls:
    login:
      pattern: api/login
      anonymous: true
    api:
      pattern: ^/api
      logout:
        logout_path: /api/logout
        invalidate_session: true
      jwt:
        use_forward: false
        require_previous_session: false
        stateless: true
