security:
  jwt:
    secret_key: secret_key
    life_time: 86400
    options:
      username_claim: sub
      header_name: X-Access-Token
      token_prefix: Bearer
  firewalls:
    login:
      pattern: login|register|oauth
      anonymous: true
    secured:
        pattern: ^.*$
        logout:
          logout_path: /logout,
        jwt:
            use_forward: true
            require_previous_session: false
            stateless: true
